Move main logic into function.

diff --git a/dotdotdot b/dotdotdot
--- a/dotdotdot
+++ b/dotdotdot
@@ -7,13 +7,16 @@ AUTO_CHMOD=true
 DOTLOG="dot.log"
 _SCRIPT_DEBUG=false
 
+
 #
-# Dependencies
+# Utility Functions/Values
 #
 
 DOTLOG_ENABLED=false
 CURR_USER=$(whoami)
 
+
+# Locking:
 # Locking code modified from https://stackoverflow.com/a/1985512
 LOCKFD=99
 exit_unlock() { flock -u $LOCKFD; exit $1; }
@@ -21,7 +24,8 @@ _prepare_locking() { eval "exec $LOCKFD>\"$1\""; trap exit_unlock EXIT; }
 # Obtain an exclusive lock immediately or fail:
 exlock_now() { _prepare_locking $1; flock -xn $LOCKFD; }
 
-# Color Output
+
+# Output and Logging:
 COLOR_INFO=$(printf "\e[0;94m")
 COLOR_WARN=$(printf "\e[0;93m")
 COLOR_ERROR=$(printf "\e[0;91m")
@@ -47,6 +51,8 @@ _info()  { echo -e "$COLOR_INFO$2$1$COLOR_NULL"; _log "INFO" "$1"; }
 _warn()  { echo -e "$COLOR_WARN$2$1$COLOR_NULL"; _log "WARN" "$1"; }
 _error() { echo -e "$COLOR_ERROR$2$1$COLOR_NULL";_log "ERROR" "$1"; }
 
+
+# Pretty-printing Status:
 STATUS_COLOR=("\e[1;91m" "\e[1;93m" "\e[1;92m")
 STATUS_TEXT=(" ERROR " "RUNNING" "SUCCESS")
 STATUS_ERROR=0
@@ -63,9 +69,7 @@ INDENT_PREFIX="   ║║ "
 STD_PREFIX="$COLOR_ERROR$INDENT_PREFIX$COLOR_NULL"
 
 SCREEN_WIDTH=$(tput cols)
-_print_status_row_overwrite() {
-    echo -ne "\r"
-}
+_print_status_row_overwrite() { echo -ne "\r"; }
 _print_status_row() {
     # 10 columns for the "[STATUS] "
     # 7 columns for the duration
@@ -78,7 +82,7 @@ _print_status_row() {
             echo -ne $DURATION_IMMEDIATE
             ;;
         "0")
-            echo -ne " 0.0s"
+            echo -ne "  .0s"
             ;;
         *)
             printf "%4ss" "$3"
@@ -88,15 +92,94 @@ _print_status_row() {
     echo -ne "$COLOR_NULL $1"
     head -c $cols_rem < /dev/zero | tr '\0' ' '
 }
-_print_status_row_next() {
-    echo
+_print_status_row_next() { echo; }
+
+
+# MAIN SYNC FUNCTION
+_dotdotdot_sync() {
+    # Loop over all .dotsh files
+    while read -r scname; do
+        scname="${scname#./}"
+        scpath="$DOTROOT/$scname"
+        scdir="$(dirname $scpath)/"
+        
+        _log
+        _debug "With $scname"
+        _debug "      at $scpath"
+        _debug "    from $scdir"
+
+        # Check if we have exec permissions on the file, and chmod
+        # if AUTO_CHMOD is set.
+        if [[ ! -x "$scpath" ]]; then
+            _debug "  script is not executable."
+            if [[ "$AUTO_CHMOD" == true ]]; then
+                # Make sure you are the file owner:
+                scuser="$(stat -c %U $scpath)"
+                if [[ "$scuser" == "$CURR_USER" ]]; then
+                    chmod u+x $scpath
+                    if [[ 0 -eq $? ]]; then
+                        _debug "  changed permissions successfully."
+                    else
+                        _debug "  failed to change permissions."
+                        _print_status_row $scname $STATUS_ERROR
+                        _print_status_row_next
+                        _warn "    Automatic CHMOD of '$scpath' failed."                    
+                        continue
+                    fi
+                else
+                    _print_status_row $scname $STATUS_ERROR 
+                    _print_status_row_next
+                    _error "Cannot automatically chmod '$scpath' because the file is owned by $scuser; you are $CURR_USER. Halting..."
+                    exit_unlock 1
+                fi
+            fi
+        fi
+
+        time_start="$(date +%s.%N)"
+
+        _print_status_row $scname $STATUS_WAITING
+        scoutf=$(mktemp)
+        scerrf=$(mktemp)
+        _debug "Running $scname"
+        ( cd $scdir; "./$(basename $scname)" >"$scoutf" 2>$scerrf ) & 
+        wait $!
+        scexit=$?
+
+        duration=$(echo "scale=1; ($(date +%s.%N) - $time_start)/1" | bc -l)
+
+        _print_status_row_overwrite
+        # Check success
+        if [[ 0 -eq $scexit ]]; then
+            _print_status_row $scname $STATUS_SUCCESS $duration
+            _print_status_row_next
+            _log "DEBUG" "output:" "$INDENT_PREFIX"
+            _log_copy "$scoutf"
+            _log "DEBUG" "error:" "$INDENT_PREFIX"
+            _log_copy "$scerrf"
+        else
+            _print_status_row $scname $STATUS_ERROR $duration
+            _print_status_row_next
+            echo "$COLOR_ERROR$INDENT_START$COLOR_NULL"
+            _error "failed with code $scexit" "$INDENT_PREFIX" 
+            _error "output:" "$INDENT_PREFIX"
+            cat "$scoutf" | sed -e "s/^/$STD_PREFIX/"
+            _log_copy "$scoutf"
+            _error "error:" "$INDENT_PREFIX"
+            cat "$scerrf" | sed -e "s/^/$STD_PREFIX/"
+            _log_copy "$scerrf"
+            echo "$COLOR_ERROR$INDENT_END$COLOR_NULL"
+        fi
+
+        rm "$scoutf"
+        rm "$scerrf"
+
+    done <<< "$(cd $DOTROOT; find . -type f | grep .*\.dotsh$;)"
 }
 
 #
 # Start of Script
 #
 
-# Check if the directory has a .dotdotdot file:
 # From https://stackoverflow.com/a/246128
 DOTROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/dotfiles"
 
@@ -150,82 +233,6 @@ if [[ $DOTLOG != "" ]]; then
 fi
 
 
-# Loop over all .dotsh files
-while read -r scname; do
-    scname="${scname#./}"
-    scpath="$DOTROOT/$scname"
-    scdir="$(dirname $scpath)/"
-    
-    _log
-    _debug "With $scname"
-    _debug "      at $scpath"
-    _debug "    from $scdir"
-
-    # Check if we have exec permissions on the file, and chmod
-    # if AUTO_CHMOD is set.
-    if [[ ! -x "$scpath" ]]; then
-        _debug "  script is not executable."
-        if [[ "$AUTO_CHMOD" == true ]]; then
-            # Make sure you are the file owner:
-            scuser="$(stat -c %U $scpath)"
-            if [[ "$scuser" == "$CURR_USER" ]]; then
-                chmod u+x $scpath
-                if [[ 0 -eq $? ]]; then
-                    _debug "  changed permissions successfully."
-                else
-                    _debug "  failed to change permissions."
-                    _print_status_row $scname $STATUS_ERROR
-                    _print_status_row_next
-                    _warn "    Automatic CHMOD of '$scpath' failed."                    
-                    continue
-                fi
-            else
-                _print_status_row $scname $STATUS_ERROR 
-                _print_status_row_next
-                _error "Cannot automatically chmod '$scpath' because the file is owned by $scuser; you are $CURR_USER. Halting..."
-                exit_unlock 1
-            fi
-        fi
-    fi
-
-    time_start="$(date +%s.%N)"
-
-    _print_status_row $scname $STATUS_WAITING
-    scoutf=$(mktemp)
-    scerrf=$(mktemp)
-    _debug "Running $scname"
-    ( cd $scdir; "./$(basename $scname)" >"$scoutf" 2>$scerrf ) & 
-    wait $!
-    scexit=$?
-
-    duration=$(echo "scale=1; ($(date +%s.%N) - $time_start)/1" | bc -l)
-
-    _print_status_row_overwrite
-    # Check success
-    if [[ 0 -eq $scexit ]]; then
-        _print_status_row $scname $STATUS_SUCCESS $duration
-        _print_status_row_next
-        _log "DEBUG" "output:" "$INDENT_PREFIX"
-        _log_copy "$scoutf"
-        _log "DEBUG" "error:" "$INDENT_PREFIX"
-        _log_copy "$scerrf"
-    else
-        _print_status_row $scname $STATUS_ERROR $duration
-        _print_status_row_next
-        echo "$COLOR_ERROR$INDENT_START$COLOR_NULL"
-        _error "failed with code $scexit" "$INDENT_PREFIX" 
-        _error "output:" "$INDENT_PREFIX"
-        cat "$scoutf" | sed -e "s/^/$STD_PREFIX/"
-        _log_copy "$scoutf"
-        _error "error:" "$INDENT_PREFIX"
-        cat "$scerrf" | sed -e "s/^/$STD_PREFIX/"
-        _log_copy "$scerrf"
-        echo "$COLOR_ERROR$INDENT_END$COLOR_NULL"
-    fi
-
-    rm "$scoutf"
-    rm "$scerrf"
-
-done <<< "$(cd $DOTROOT; find . -type f | grep .*\.dotsh$;)"
+_dotdotdot_sync
 
 exit_unlock 0
